base:
  use_cuda: True

data:
  data_folder: data
  images_folder: train
  train_dataset: dev.json
  val_dataset: dev.json
  test_dataset: test.json
  num_worker: 2

tokenizer:
  padding: max_length
  max_length: 20
  truncation: True
  return_token_type_ids: True
  return_attention_mask: True

text_embedding:
  text_encoder: bert-base-multilingual-uncased
  freeze: True
  d_features: 768
  d_model: 512
  dropout: 0.1

vision_embedding:
  image_encoder: google/vit-base-patch16-224-in21k
  freeze: True
  d_features: 768
  d_model: 512
  dropout: 0.1

attention:
  layers: 4
  heads: 16
  d_model: 512
  d_key: 64
  d_value: 64
  d_ff: 2048
  d_feature: 2048
  dropout: 0.1
  use_aoa: False

encoder:
  d_model: 512
  layers: 4
  heads: 16

decoder:
  text_decoder: bert-base-multilingual-uncased
  padding: max_length
  max_length: 5
  truncation: True
  d_model: 768
  layers: 4
  heads: 16
  dropout: 0.1

model:
  name: mbert-vit  # Custom name for the multimodal model
  type_model: "gen"
  intermediate_dims: 512
  dropout: 0.1

train:
  output_dir: checkpoint
  seed: 12345
  num_train_epochs: 100
  patience: 5
  learning_rate: 0.0001
  weight_decay: 0.0
  warmup_ratio: 0.0
  warmup_steps: 0
  metric_for_best_model: f1
  per_device_train_batch_size: 8
  per_device_valid_batch_size: 8
  per_device_eval_batch_size: 8

inference:
  checkpoint: checkpoint-3